# Settings for ros_control control loop
hardware_control_loop:
  loop_hz: &loop_hz 125

# Settings for ros_control hardware interface
ur_hardware_interface:
  joints: &robot_joints
    - left_shoulder_pan_joint
    - left_shoulder_lift_joint
    - left_elbow_joint
    - left_wrist_1_joint
    - left_wrist_2_joint
    - left_wrist_3_joint

# Publish all joint states
joint_state_controller_left:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_hz

# Publish wrench
force_torque_sensor_controller_left:
  type: force_torque_sensor_controller/ForceTorqueSensorController
  publish_rate: *loop_hz

# Publish speed_scaling factor
speed_scaling_state_controller_left:
  type: scaled_controllers/SpeedScalingStateController
  publish_rate: *loop_hz

# Joint Trajectory Controller - position based
scaled_pos_joint_traj_controller_left:
  type: position_controllers/ScaledJointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
    left_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
    left_elbow_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20

pos_joint_traj_controller_left:
  type: position_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
    left_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
    left_elbow_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
    left_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20

scaled_vel_joint_traj_controller_left:
  type: velocity_controllers/ScaledJointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    left_elbow_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    left_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  velocity_ff:
    left_shoulder_pan_joint: 1.0
    left_shoulder_lift_joint: 1.0
    left_elbow_joint: 1.0
    left_wrist_1_joint: 1.0
    left_wrist_2_joint: 1.0
    left_wrist_3_joint: 1.0
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20

vel_joint_traj_controller_left:
  type: velocity_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    left_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    left_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    left_elbow_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    left_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  gains:
    left_shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    left_wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
  velocity_ff:
    left_shoulder_pan_joint: 1.0
    left_shoulder_lift_joint: 1.0
    left_elbow_joint: 1.0
    left_wrist_1_joint: 1.0
    left_wrist_2_joint: 1.0
    left_wrist_3_joint: 1.0
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 20

# Joint Group Velocity Controller
joint_group_vel_controller_left:
  type: velocity_controllers/JointGroupVelocityController
  joints: *robot_joints

# Pass-through Controllers
forward_joint_traj_controller_left:
  type: pass_through_controllers/JointTrajectoryController
  joints: *robot_joints

forward_cartesian_traj_controller_left:
  type: pass_through_controllers/CartesianTrajectoryController
  joints: *robot_joints

# Twist Controller
twist_controller_left:
  type: ros_controllers_cartesian/TwistController
  frame_id: tool0_controller
  publish_rate: *loop_hz
  joints: *robot_joints

# Pose-Based Cartesian Trajectory Controller
pose_based_cartesian_traj_controller_left:
  type: pose_controllers/CartesianTrajectoryController
  base: base
  tip: tool0_controller
  joints: *robot_joints

# Joint-Based Cartesian Trajectory Controller
joint_based_cartesian_traj_controller_left:
  type: position_controllers/CartesianTrajectoryController
  base: base
  tip: tool0
  joints: *robot_joints

# Robot Status Controller
robot_status_controller_left:
  type: industrial_robot_status_controller/IndustrialRobotStatusController
  handle_name: industrial_robot_status_handle
  publish_rate: 10
